chapters-backend:
  git: kde:wikitolearn/wikitolearn-chapters-backend.git
course-midtier:
  git: kde:wikitolearn/wikitolearn-course-midtier.git
courses-backend:
  git: kde:wikitolearn/wikitolearn-courses-backend.git
coursessecurity-backend:
  git: kde:wikitolearn/wikitolearn-coursessecurity-backend.git
frontend:
  git: kde:wikitolearn/wikitolearn-frontend.git
math-backend:
  git: kde:wikitolearn/wikitolearn-math-backend.git
math-midtier:
  git: kde:wikitolearn/wikitolearn-math-midtier.git
pages-backend:
  git: kde:wikitolearn/wikitolearn-pages-backend.git
pdf-backend:
  git: kde:wikitolearn/wikitolearn-pdf-backend.git
pwa-gateway:
  git: kde:wikitolearn/wikitolearn-pwa-gateway.git
shared-services:
  git: kde:wikitolearn/wikitolearn-shared-services.git
