chapters-backend:
  git: kde:scratch/atundo/wikitolearn-chapters-backend.git
course-midtier:
  git: kde:scratch/atundo/wikitolearn-course-midtier.git
courses-backend:
  git: kde:scratch/atundo/wikitolearn-courses-backend.git
coursessecurity-backend:
  git: kde:scratch/atundo/wikitolearn-coursessecurity-backend.git
pages-backend:
  git: kde:scratch/atundo/wikitolearn-pages-backend.git
pwa-gateway:
  git: kde:scratch/atundo/wikitolearn-pwa-gateway.git
shared-services:
  git: kde:scratch/atundo/wikitolearn-shared-services.git
frontend:
  git: kde:scratch/cristianbaldi/wikitolearn-frontend.git
  git_branch: migration
