chapters-backend:
  git: null
course-midtier:
  git: null
courses-backend:
  git: null
coursessecurity-backend:
  git: null
pages-backend:
  git: null
pwa-gateway:
  git: null
shared-services:
  git: null
